spring:
  application:
   name: springBatch
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    initialize-schema: always
  h2:
    console:
      enabled: true         # Enable the H2 Console
      path: /h2-console

server:
  port: 8080
